name: Run RSpec tests

on:
  push:
  pull_request:

permissions:
  issues: write
  pull-requests: write

jobs:
  rspec:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && steps.check_pr.outputs.pr_exists == '0' || github.event_name == 'pull_request' }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.4'
    - name: Install dependencies
      run: bundle install
    - name: Run RSpec
      id: rspec
      continue-on-error: true
      run: |
        bundle exec rspec -f j -o tmp/rspec_results.json -f p
        if [ $? -ne 0 ]; then
          echo "RSpec failed"
          exit 1
        fi
    - name: RSpec Report
      uses: SonicGarden/rspec-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        json-path: tmp/rspec_results.json
      if: github.event_name == 'pull_request'

    - name: Fail the build if tests failed
      if: failure()
      run: exit 1
